[package]
name = "micro-rdk"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

links = "micro_rdk"


[lib]
crate-type = ["lib"]

[features]
default = []
camera = []
esp32 = ["dep:esp-idf-svc", "dep:embedded-svc", "dep:embedded-hal"]
native = ["dep:rustls", "dep:webpki-roots", "dep:rustls-pemfile", "dep:mdns-sd", "dep:local-ip-address", "dep:openssl", "dep:rcgen", "dep:async-std-openssl"]

[dev-dependencies]
test-log.workspace = true
env_logger.workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-channel.workspace = true
async-io.workspace = true
bytes.workspace = true
either.workspace = true
embedded-hal = { workspace = true, optional = true }
embedded-svc = { workspace = true, optional = true }
esp-idf-svc = { workspace = true, optional = true }
futures.workspace = true
futures-lite.workspace = true
h2.workspace = true
hyper.workspace = true
lazy_static.workspace = true
local-ip-address = { workspace = true, optional = true }
log.workspace = true
mdns-sd = { workspace = true, optional = true }
prost.workspace = true
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
sctp-proto.workspace = true
smol.workspace = true
smol-timeout.workspace = true
sdp.workspace = true
socket2.workspace = true
tokio.workspace = true
webpki-roots = { workspace = true, optional = true }
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
rcgen = { workspace = true, optional = true }
sha2.workspace = true
stun_codec.workspace = true
bytecodec.workspace = true
trackable.workspace = true
openssl = { workspace = true, optional = true }
async-std-openssl = { workspace = true, optional = true }
thiserror.workspace = true
pin-project-lite.workspace = true
url.workspace = true
once_cell.workspace = true
chrono.workspace = true
micro-rdk-macros.workspace = true
ignore.workspace = true
bitfield.workspace = true
scopeguard.workspace = true

[build-dependencies]
anyhow.workspace = true
const-gen.workspace = true
embuild.workspace = true
