[package]
name = "{{project-name}}"
version = "0.2.5"
edition = "2021"
authors = ["{{authors}}"]
resolver = "2"
rust-version = "1.75"

[dependencies]
micro-rdk = {git = "https://github.com/viamrobotics/micro-rdk.git", features = ["{{mcu}}"], version = "0.2.5", rev = "a400ef2"}

[package.metadata.com.viam]
module = true
