[package]
name = "{{project-name}}"
version = "0.1.9-rc3"
edition = "2021"
authors = ["{{authors}}"]
resolver = "2"
rust-version = "1.75"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"


[dependencies]
embedded-svc = "0.27"
embedded-hal = { version = "0.2.7", features = ["unproven"]}
log = "0.4"
async-channel = "2"
futures-lite = "1"
micro-rdk = {version = "0.1.9-rc3", git = "https://github.com/viamrobotics/micro-rdk.git", features = ["esp32", "binstart","provisioning"], rev = "4f0814a" }

[build-dependencies]
cargo_metadata = "0.18"
embuild = "0.29"
