name: License Finder

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ['main']
  push:

jobs:
  license_finder:
    name: Audit 3rd-Party Licenses
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install toolchain deps
        run: sudo apt-get install -y git curl gcc clang ninja-build cmake libudev-dev unzip xz-utils python3 python3-pip python3-venv libusb-1.0-0 libssl-dev pkg-config libpython2.7

      - name: Install esp32 toolchain
        run: curl -LO https://github.com/esp-rs/rust-build/releases/download/v1.66.0.0/install-rust-toolchain.sh && chmod a+x install-rust-toolchain.sh && ./install-rust-toolchain.sh && . ./export-esp.sh

      - name: Run license finder
        run: license_finder
